spring:
  datasource:
    url: jdbc:h2:mem:test-db
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console.enabled: true